#! /bin/sh
### BEGIN INIT INFO
# Provides:		sentinel-server
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Required-Start:
# Required-Stop:
# Short-Description:	sentinel-server - Redis monitor
# Description:		sentinel-server - Redis monitor
### END INIT INFO

DAEMON="/usr/bin/redis-server"
DAEMON_ARGS="/etc/redis/sentinel.conf --sentinel"
NAME="sentinel-server"
DESC="sentinel-server"

RUNDIR="/var/run/redis"
PIDFILE="$RUNDIR/sentinel-server.pid"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	touch $PIDFILE
	chown redis:redis $RUNDIR $PIDFILE

	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	sleep 1
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  status)
	echo -n "$DESC is "
	if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
	then
		echo "running"
	else
		echo "not running"
		exit 1
	fi
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
